### ISSUE TITLE
Matlab load does not work if 2D data has been zero-filled in both dimensions

### ISSUE THREAD

**Issue by wfranssen** [smeerten/ssnake#10]
If 2D data is zerofilled in both dimensions and saved as a .mat file, it cannot be loaded, as it gives an error with the statement:

xaxA = [k[0] for k in (mat['xaxArray'][0,0][0])]
IndexError: invalid index to scalar variable.

**Comment by smeerten** [comment]
I cannot reproduce this bug.
Are you sure it is related to the zero filling of the data?
Could you upload some example data and the processing steps you've used?

**Comment by wfranssen** [comment]
- Open file
- set size in D2 to 2k
- set size in D1 to 2k
- save as matlab
- open the saved file

All done under python3 (and using latest commit).

[2D.mat.zip](https://github.com/smeerten/ssnake/files/98006/2D.mat.zip)
