### ISSUE TITLE
Custom axis lost if decreasing the size of the spectrum

### ISSUE THREAD

**Issue by Famlam** [smeerten/ssnake#122]
1. Have an incomplete T1 measurement (e.g. t=[0.1 0.2 0.4 0.8 1.6 3.2 6.4 12.8] seconds, size = 8, but data points were only measured up to 6.4, so the last point is all zeros and you want to get rid of it)
2. Set a custom axis equaling `t`
3. Change the size of your spectrum to 7 rather than 8
4. Notice the custom axis is discarded

Request:
When changing the size of a spectrum with a custom axis to a smaller value, preserve the (still applicable) X-axis values

**Comment by wfranssen** [comment]
Good suggestion. I pushed a commit to fix this.
