### ISSUE TITLE
Add option to preserve processing history

### ISSUE THREAD

**Issue by Famlam** [smeerten/ssnake#126]
Would it be possible to add a preference to automatically save the processing history (textual, as accessible via History -> History) to the saved file (JSON and/or Matlab)?

Steps to reproduce where this would be useful:
1. Make a mistake (e.g. forgetting to shift a FID 1 point or something else subtle)
2. Save file and ignore it for a while
3. Return to file 2 years later
4. Wonder why the spectrum doesn't match new data
5. (Reprocess and never find out what went wrong in the past... or is the new processing wrong... you don't know)

**Comment by wfranssen** [comment]
Hi Famlam,

This is actually already stored in the matlab/json file under the field 'History'. If you reload the data from the matlab/json in ssnake, you can view it via History -> History.

**Comment by Famlam** [comment]
Oops... must've loaded really old data I guess :S
Thank you!
