### ISSUE TITLE
Double pop-up boxes created from NMR periodic table

### ISSUE THREAD

**Issue by RyanJMcCarty** [smeerten/ssnake#79]
When clicking options in the NMR periodic table, double popup boxes are created when any of the buttons are pressed (such as "details" and "list"). This is using the GUI version installed from with windows exe. Python 3.7.2, Windows 10.

**Comment by wfranssen** [comment]
Confirmed for ssNake installer v1.1 on windows 7. v1.0 does work however. There is no change in code between current master and v1.0 when it comes to the NMR table. Perhaps the issue is due to a new version of Qt used for the v1.1 build...

**Comment by wfranssen** [comment]
Running v1.0 with new pyqt (5.12.2) indeed cause the same issue. Clearly something changed with the new pyqt.
